[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
thookvault = "3jitQYi1NVz1Sfa2gy2pe7Gvf2LEC17jg5H9od46ACW4"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
